### ISSUE TITLE
Support for searching ods (libreoffice files)

### ISSUE THREAD

**Issue by majuwa** [zazuum/xlsxgrep#1]
Hi,
it might be useful to also search through LibreOffice Calc (ods) files. There are some python libraries like [pyexcel ](http://docs.pyexcel.org/en/latest/index.html), which might help in this regard. In a [fork ](https://github.com/majuwa/xlsxgrep) of your project. I applied this and at least for my use cases, it works. If you are interested in the changes, I can create a pull request.

**Comment by zazuum** [comment]
Hi,
Thank you for your suggestion. That's a useful feature and I'm interested in the changes so please do pull request.
