### ISSUE TITLE
UserWarning on searches

### ISSUE THREAD

**Issue by thezoggy** [zazuum/xlsxgrep#10]
Is there a way to suppress the UserWarning ?

```
#python3 -V
Python 3.9.9

#xlsxgrep -V
xlsxgrep  0.0.25


#xlsxgrep -H -r 123456789 *
/usr/local/lib/python3.9/site-packages/openpyxl/worksheet/_reader.py:312: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
/usr/local/lib/python3.9/site-packages/openpyxl/worksheet/_reader.py:312: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
```

**Comment by thezoggy** [comment]
looks like you could change where user warnings are sent to or just stop them. personally i'd like an argument to suppress them for automation sake to keep output cleaner
https://stackoverflow.com/questions/54976991/python-openpyxl-userwarning-unknown-extension-issue

**Comment by zazuum** [comment]
With what kind of file extensions(xls,xlsx or ods) you get these warnings? 
I would really appreciate if you have any dummy sample file so I could replicate the and test the issue.
Thanks.

**Comment by thezoggy** [comment]
[example.xlsx](https://github.com/zazuum/xlsxgrep/files/8157178/example.xlsx)

created minimal example to show that it works but has warning about the sheet having 'data validation':
```
#xlsxgrep example example.xlsx
/usr/local/lib/python3.9/site-packages/openpyxl/worksheet/_reader.py:312: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
internet	example
```

**Comment by thezoggy** [comment]
attaching another example, this one has validation and external linked content which I think is the cause for the other warning

[example2.xlsx](https://github.com/zazuum/xlsxgrep/files/8157236/example2.xlsx)

```
#xlsxgrep example example2.xlsx
/usr/local/lib/python3.9/site-packages/openpyxl/worksheet/_reader.py:312: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
/usr/local/lib/python3.9/site-packages/openpyxl/worksheet/_reader.py:312: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
example
```

**Comment by zazuum** [comment]
Thanks. 

I just tested with both files and was able to replicate the issue. To suppress errors you should just redirect errors to stderr.
For example: `xlsxgrep 'blah' 2> /dev/null`

This issue is resolved in current version on request:  [https://github.com/zazuum/xlsxgrep/issues/7](https://github.com/zazuum/xlsxgrep/issues/7)

**Comment by thezoggy** [comment]
I agree I could do that if I was using bash or a shell that supported the redirection that would be a way to work around it but sadly I am not.

**Comment by zazuum** [comment]
What shell you have?
In Windows Powershell you could easily suppress warnings with redirecting stderr to null with: `xlsxgrep 'blah' 2>  $NUL`

**Comment by thezoggy** [comment]
I use csh/tcsh (carry over from solaris and old mac days)

**Comment by zazuum** [comment]
UserWarning is suppressed by default now.
You can do update with: ```pip install -U xlsxgrep```
Cheers.
