### ISSUE TITLE
Increase max sessions

### ISSUE THREAD

**Issue by sh3ll4rpw** [zazuum/xlsxgrep#12]
OS: Ubuntu 22.04
python: 3.10
pip: 22.3.1
xlsxgrep: 0.0.28
RAM: 32GB
CPU: Intel Xeon with 18 cores 

I'm searching through 3000 excel files on different terms but this tool is much slower than pdfgrep or something like that. It takes a whole day for 1 search and there are many files I need to check. Because of that I wanted to create multiple sessions with tmux. But xlsxgrep only support 3 sessions? When I create a 4th session with xlsxgrep it says the xlsxgrep process is "Killed" on the previous started session". Please increase max sessions and preferably increase the speed

**Comment by sh3ll4rpw** [comment]
Maybe it's an idea to add function that start multiple threads

**Comment by sh3ll4rpw** [comment]
I guess multiple threads is not going to work since XLSX is very heavy on memory for some reason.

$ dmesg -T| grep -E -i -B100 'killed process'
[Mon Jan  2 14:37:27 2023] Out of memory: Killed process 347179 (xlsxgrep) total-vm:30210216kB, anon-rss:30086148kB, file-rss:2228kB, shmem-rss:0kB, UID:1000 pgtables:59176kB oom_score_adj:0

**Comment by zazuum** [comment]
xlsxgrep is not session limited, you can run as many sessions as your system can handle.
There might some optimization can be done to increase the speed but not too much because as you already figured out xlsx files can be very heavy on system resources sometimes even with native processing applications and there's not much can be done at the moment. 
Anyway, I'll perform some test when I find some time and see.

**Comment by sh3ll4rpw** [comment]
Haha yes I see. 28GB RAM for 3 xlsxgrep sessions. With this little sessions it takes me a long time to get through all files. Anyway, thank you for the tool, I couldn't do my work without!

**Comment by zazuum** [comment]
Yeah, 28 GB RAM is way too much. This memory issue is actually related with issue #13 you reported already.
I will hopefully provide a fix for this soon.
Cheers.

**Comment by zazuum** [comment]
Memory issues are now fixed in new version.
Cheers.
