### ISSUE TITLE
-Z option

### ISSUE THREAD

**Issue by sh3ll4rpw** [zazuum/xlsxgrep#14]
Please add -Z option

**Comment by sh3ll4rpw** [comment]
Reason: with -Z it's easier to use xargs with -0. Now I need to use ":" as delimiter with awk to get the file names. But when the output of the matches found with xlsxgrep contain ":" I get text between my list of file names which results in errors with xargs cp. I would prefer -Z more than a working -l because I like to see some context around the match. It gives me a better view of the match

**Comment by zazuum** [comment]
New option (-Z) is now added in new version.
Thank you for suggestion.
Cheers.
