### ISSUE TITLE
A few warning are written to stdout instead of ignored

### ISSUE THREAD

**Issue by sh3ll4rpw** [zazuum/xlsxgrep#15]
OS: Ubuntu 22.04
python: 3.10
pip: 22.3.1
xlsxgrep: 0.0.28

I used `xlsxgrep -riH` and put my output to a file with >>. I wanted to create a pipe with commands but the warnings in the output breaks my pipe.

Stdout of xlsxgrep ignores all errors expect for:
```
WARNING *** file size (36373) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
```
These errors are piped or added to the file I write the output to. I don't know exactly where this error come from but the only command I ran is xlsxgrep -riH PATTERN PATH >> output.txt.

**Comment by zazuum** [comment]
Warnings and errors in output are normal, they may warn if files are corrupted, password protected or warn about limited support to charts, drawings and similar. However you can suppress all errors or redirect them to /dev/null or to another file for example:

xlsxgrep PATTERN PATH -riH 2>> /dev/null

or

xlsxgrep PATTERN PATH -riH 1>> Report.csv 2>> logs-error.txt

**Comment by sh3ll4rpw** [comment]
Shouldn't errors be written to the stderr instead of stdout? I'm currently piping stdout to xargs to copy the files, but it crashes since these errors have no file path. I solved it with including this command to the pipe:
`sed "/^WARNING \*\*\*/d" |`

**Comment by zazuum** [comment]
Yes, you're right. Errors should be written to stderr, however these are logging warnings so that's why you can see them in the stdout. 
Thanks for report. I will disable logging warnings in the next version.

**Comment by zazuum** [comment]
Logging warnings are now disabled in new version.
Cheers.
