### ISSUE TITLE
Request: Print to stderr?

### ISSUE THREAD

**Issue by supercheetah** [zazuum/xlsxgrep#7]
I really do appreciate this little script.  It really comes in handy.

Can I request for error messages to be printed to `stderr` so that `xlsxgrep 'blah' 2> /dev/null` will properly suppress error messages? It should be a simple matter of replacing the appropriate `print()` lines with `print("Error:  Something went wrong...", file=sys.stderr)`.

I'm considering creating a pull request when I have some time to look at this, but if someone else gets around to it before me, please do!

**Comment by zazuum** [comment]
Sure, will do when I find some time.

**Comment by zazuum** [comment]
Print error messages to sderr is now supported.
Thank you for your suggestion.
Cheers.
